### PR TITLE
Check if there is a hint exception defined

### LINKED ISSUE #2: I'm getting a PHP warming message when the Hint exception is null
Hi,

While developing locally, I have the PHP warnings enabled. I'm getting the following warning message because of that:

```
Exception: Warning: Attempt to read property "exception" on null in magento2/vendor/justbetter/magento2-sentry-filter-events/Observer/BeforeSending.php on line 33 in magento2/vendor/magento/framework/App/ErrorHandler.php:62
```

Is that expected to be `null` at that point?

### PR DESCRIPTION
**Pull request by rbnmulder**

### CODE REVIEW

File: Observer/BeforeSending.php [hunk 1]
```diff
@@ -30,16 +30,18 @@ public function execute(Observer $observer): void
...
+            }
 
-        $messages = $this->json->unserialize($this->scopeConfig->getValue('sentry/event_filtering/messages'));
-        foreach ($messages as $message) {
-            if (str_contains($hintMessage, $message['message'])) {
-                $observer->getEvent()->getSentryEvent()->unsEvent();
+            $messages = $this->json->unserialize($this->scopeConfig->getValue('sentry/event_filtering/messages'));
+            foreach ($messages as $message) {
+                if (str_contains($hintMessage, $message['message'])) {
+                    $observer->getEvent()->getSentryEvent()->unsEvent();
```
Comment (indykoning) [inline Observer/BeforeSending.php]: Once we've unset the event there is no reason to keep looping, correct?
It may be a good idea to break out of the loop in that case 🙂 
```suggestion
                    $observer->getEvent()->getSentryEvent()->unsEvent();
                    break;
```

File: Observer/BeforeSending.php [hunk 2]
```diff
@@ -30,16 +30,18 @@ public function execute(Observer $observer): void
...
-        if ($hint->exception instanceof LocalizedException) {
-            $hintMessage = $hint->exception->getRawMessage();
-            $event->setMessage($hintMessage);
-        }
+        if ($hint?->exception !== null) {
+            $hintMessage = $hint->exception->getMessage();
+            if ($hint->exception instanceof LocalizedException) {
+                $hintMessage = $hint->exception->getRawMessage();
+                $event->setMessage($hintMessage);
+            }
```
Comment (indykoning) [inline Observer/BeforeSending.php]: Aren't we able to get the message some other way when we do not have the exception, like getting it from the Event itself?
Then at least we will be able to continue to filter out events even without hint.
```suggestion
        $hintMessage = $hint?->exception?->getMessage() ?? $event->getMessage();
        if ($hint?->exception instanceof LocalizedException) {
            $hintMessage = $hint->exception->getRawMessage() ;
            $event->setMessage($hintMessage);
        }
```

Otherwise i would suggest flipping the logic of the if and returning early to reduct the depth of if/else
```suggestion
        if ($hint?->exception === null) {
            return
        }
        $hintMessage = $hint->exception->getMessage();
        if ($hint->exception instanceof LocalizedException) {
            $hintMessage = $hint->exception->getRawMessage();
            $event->setMessage($hintMessage);
        }
```
